"use client";

import * as React from "react";
import { Download, Sparkles, Wand, Copy } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";

import { generateAllAction, generateSectionAction, fixCodeAction } from "@/app/actions";
import { CodeEditor } from "@/components/pygenius/CodeEditor";
import { ContextDialog } from "@/components/pygenius/ContextDialog";
import { CodeEditorCard } from "@/components/pygenius/CodeEditorCard";
import { LoadingSpinner } from "@/components/pygenius/LoadingSpinner";
import type { ActionInfo, AllFilesContent, FileContent, LoadingStates } from "@/components/pygenius/types";
import type { FileType } from "@/ai/flows/types";

const initialAllFilesContent: AllFilesContent = {
  "api.py": { header: "", middle: "", footer: "" },
  "schema.py": { header: "", middle: "", footer: "" },
  "logic.py": { header: "", middle: "", footer: "" },
};

export default function PyGeniusGenerator() {
  const { toast } = useToast();
  const [isPending, startTransition] = React.useTransition();
  
  const [fileType, setFileType] = React.useState<FileType>('api.py');
  const [allFilesContent, setAllFilesContent] = React.useState<AllFilesContent>(initialAllFilesContent);
  const [singlePrompt, setSinglePrompt] = React.useState("");

  const [dialogOpen, setDialogOpen] = React.useState(false);
  const [dialogContext, setDialogContext] = React.useState("");
  const [currentAction, setCurrentAction] = React.useState<ActionInfo>(null);
  
  const [loading, setLoading] = React.useState<LoadingStates>({
    all: false,
    headerGen: false, headerFix: false,
    middleGen: false, middleFix: false,
    footerGen: false, footerFix: false,
  });

  const anyLoading = isPending || Object.values(loading).some(Boolean);
  
  const currentContent = allFilesContent[fileType];

  const getCombinedContext = (optionalContext: string) => {
    let otherFilesContext = "";
    for (const ft in allFilesContent) {
      if (ft !== fileType) {
        const content = allFilesContent[ft as FileType];
        otherFilesContext += `
--- Content of ${ft} ---
Header:
${content.header}
Middle:
${content.middle}
Footer:
${content.footer}
---
`;
      }
    }

    return `
      User provided context: ${optionalContext}

      ${otherFilesContext}
    `;
  }
  
  const handleContentChange = (section: keyof FileContent, value: string) => {
    setAllFilesContent(prev => ({
      ...prev,
      [fileType]: {
        ...prev[fileType],
        [section]: value,
      }
    }));
  };

  const triggerAction = (actionInfo: NonNullable<ActionInfo>) => {
    if (actionInfo.type === 'generate-all') {
      handleGenerateAll(""); // No context needed for generate-all from dialog
      return;
    }
    setCurrentAction(actionInfo);
    setDialogContext("");
    setDialogOpen(true);
  }

  const handleDialogConfirm = () => {
    if (!currentAction) return;

    if (currentAction.type === 'generate-all') {
       // This case is handled directly by triggerAction
    } else if (currentAction.type === 'generate-section' && currentAction.section) {
      handleGenerateSection(currentAction.section, dialogContext);
    } else if (currentAction.type === 'fix-code' && currentAction.section) {
      handleFixCode(currentAction.section, dialogContext);
    }
  };

  const handleGenerateAll = (context: string) => {
    if (!singlePrompt) {
      toast({ title: "Prompt is empty", description: "Please enter a prompt to generate the full file.", variant: "destructive" });
      return;
    }
    setLoading(prev => ({ ...prev, all: true }));
    startTransition(async () => {
      const result = await generateAllAction({ prompt: singlePrompt, context: getCombinedContext(context) });
      if (result.success && result.data) {
        setAllFilesContent({
          "api.py": result.data.api,
          "schema.py": result.data.schema,
          "logic.py": result.data.logic,
        });
        toast({ title: "Files Generated", description: "All three files have been generated by AI." });
      } else {
        toast({ title: "Error", description: result.error, variant: "destructive" });
      }
      setLoading(prev => ({ ...prev, all: false }));
    });
  };

  const handleGenerateSection = (section: keyof FileContent, context: string) => {
    const loadingKey = `${section}Gen` as keyof LoadingStates;
    setLoading(prev => ({ ...prev, [loadingKey]: true }));
    startTransition(async () => {
      const result = await generateSectionAction({ 
        sectionToGenerate: section,
        header: currentContent.header, 
        middle: currentContent.middle, 
        footer: currentContent.footer, 
        context: getCombinedContext(context), 
        fileType 
      });
      if (result.success && result.data) {
        setAllFilesContent(prev => ({
          ...prev,
          [fileType]: {
            header: result.data.header,
            middle: result.data.middle,
            footer: result.data.footer,
          }
        }));
        toast({ title: `${section.charAt(0).toUpperCase() + section.slice(1)} Generated`, description: `The ${section} section for ${fileType} has been generated.` });
      } else {
        toast({ title: "Error", description: result.error, variant: "destructive" });
      }
      setLoading(prev => ({ ...prev, [loadingKey]: false }));
    });
  };

  const handleFixCode = (section: keyof FileContent, context: string) => {
    const codeToFix = currentContent[section];
    if (!codeToFix) {
      toast({ title: "Section is empty", description: `Please enter or generate code in the ${section} section to fix it.`, variant: "destructive" });
      return;
    }
    const loadingKey = `${section}Fix` as keyof LoadingStates;
    setLoading(prev => ({ ...prev, [loadingKey]: true }));
    startTransition(async () => {
      const result = await fixCodeAction({ 
        code: codeToFix, 
        context: getCombinedContext(context),
        fileType,
        section,
      });
      if (result.success && result.data) {
        handleContentChange(section, result.data.fixedCode);
        toast({ title: "Code Fixed", description: result.data.explanation || `The ${section} section has been improved by AI.` });
      } else {
        toast({ title: "Error", description: result.error, variant: "destructive" });
      }
      setLoading(prev => ({ ...prev, [loadingKey]: false }));
    });
  };
  
  const handleCopy = async (content: string, title: string) => {
    try {
      await navigator.clipboard.writeText(content);
      toast({ title: `Copied ${title}`, description: `${title} content copied to clipboard.` });
    } catch (err) {
      console.error('Failed to copy text: ', err);
      toast({ title: "Copy Failed", description: "Could not copy content to clipboard.", variant: "destructive" });
    }
  };
  
  const handleCopySection = (section: keyof FileContent) => {
    const content = currentContent[section];
    if (content) {
      handleCopy(content, `${section.charAt(0).toUpperCase() + section.slice(1)} Section`);
    }
  };

  const handleCopyAll = () => {
    const fileContent = `# Header\n${currentContent.header}\n\n# Middle\n${currentContent.middle}\n\n# Footer\n${currentContent.footer}`;
    if (fileContent) {
      handleCopy(fileContent, `${fileType}`);
    }
  };

  const handleDownload = () => {
    const fileContent = `# Header\n${currentContent.header}\n\n# Middle\n${currentContent.middle}\n\n# Footer\n${currentContent.footer}`;
    const blob = new Blob([fileContent], { type: 'text/x-python' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = fileType;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <>
      <div className="container mx-auto p-4 grid gap-4">
        <Card>
          <CardHeader className="p-4">
            <Label htmlFor="file-type-tabs" className="text-base font-semibold font-headline">Select File Type</Label>
            <CardDescription>Choose the type of Python file you want to work on.</CardDescription>
          </CardHeader>
          <CardContent className="p-4 pt-0">
            <Tabs id="file-type-tabs" value={fileType} onValueChange={(v) => setFileType(v as FileType)} className="w-full">
              <TabsList className="grid w-full grid-cols-3">
                <TabsTrigger value="api.py">api.py</TabsTrigger>
                <TabsTrigger value="schema.py">schema.py</TabsTrigger>
                <TabsTrigger value="logic.py">logic.py</TabsTrigger>
              </TabsList>
            </Tabs>
          </CardContent>
        </Card>
        
        <Card>
          <CardHeader className="p-4">
            <CardTitle className="font-headline">Generate All Files from Prompt</CardTitle>
            <CardDescription>Provide a detailed prompt and let the AI generate all three files at once. The generated code will populate the editors below.</CardDescription>
          </CardHeader>
          <CardContent className="p-4 pt-0">
            <Textarea
              value={singlePrompt}
              onChange={(e) => setSinglePrompt(e.target.value)}
              placeholder="Enter prompt..."
              className="font-body bg-card max-h-[250px]"
              disabled={anyLoading}
            />
          </CardContent>
          <CardFooter className="p-4">
            <Button onClick={() => triggerAction({ type: 'generate-all' })} disabled={anyLoading || loading.all} className="w-full sm:w-auto ml-auto">
              {loading.all ? <LoadingSpinner className="mr-2" /> : <Sparkles className="mr-2 h-4 w-4" />}
              Generate All Files
            </Button>
          </CardFooter>
        </Card>

        <div className="grid grid-cols-1 gap-4">
          <CodeEditorCard title="Header" value={currentContent.header} onChange={(value) => handleContentChange("header", value)} onGenerate={() => triggerAction({type: 'generate-section', section: 'header'})} onFix={() => triggerAction({type: 'fix-code', section: 'header'})} onCopy={() => handleCopySection("header")} isGenerating={loading.headerGen} isFixing={loading.headerFix} section="header" anyLoading={anyLoading} />
          <CodeEditorCard title="Middle" value={currentContent.middle} onChange={(value) => handleContentChange("middle", value)} onGenerate={() => triggerAction({type: 'generate-section', section: 'middle'})} onFix={() => triggerAction({type: 'fix-code', section: 'middle'})} onCopy={() => handleCopySection("middle")} isGenerating={loading.middleGen} isFixing={loading.middleFix} section="middle" anyLoading={anyLoading} />
          <CodeEditorCard title="Footer" value={currentContent.footer} onChange={(value) => handleContentChange("footer", value)} onGenerate={() => triggerAction({type: 'generate-section', section: 'footer'})} onFix={() => triggerAction({type: 'fix-code', section: 'footer'})} onCopy={() => handleCopySection("footer")} isGenerating={loading.footerGen} isFixing={loading.footerFix} section="footer" anyLoading={anyLoading} />
        </div>

        <div className="flex justify-end p-4 gap-2">
          <Button size="lg" variant="outline" onClick={handleCopyAll} disabled={anyLoading || (!currentContent.header && !currentContent.middle && !currentContent.footer)}>
            <Copy className="mr-2 h-4 w-4" />
            Copy {fileType}
          </Button>
          <Button size="lg" onClick={handleDownload} disabled={anyLoading || (!currentContent.header && !currentContent.middle && !currentContent.footer)}>
            <Download className="mr-2 h-4 w-4" />
            Download {fileType}
          </Button>
        </div>
      </div>
      
      <ContextDialog
        open={dialogOpen}
        onOpenChange={setDialogOpen}
        onConfirm={handleDialogConfirm}
        context={dialogContext}
        onContextChange={setDialogContext}
      />
    </>
  );
}
